merged

diff --git a/agent/Linux/setup/extensions/bin/agent-persona-worker b/agent/Linux/setup/extensions/bin/agent-persona-worker
--- a/agent/Linux/setup/extensions/bin/agent-persona-worker
+++ b/agent/Linux/setup/extensions/bin/agent-persona-worker
@@ -52,8 +52,13 @@ _exec_do_exec() {
 	log_info "$*"
 	local _exit_status
 	if [ -z "$dry_run" ]; then
-		"$@"
-		_exit_status=$?
+		if [ -z "$log_logfile" ]; then
+			"$@"
+			_exit_status=$?
+		else
+			"$@" 2>&1 | sed -u 's/^/    /' | tee -a "$log_logfile"
+			_exit_status=$?
+		fi
 	else
 		log_warn "using dry run status: $dry_run"
 		_exit_status=$dry_run
@@ -88,8 +93,8 @@ exit_with_error() {
 	exit_color_code="$conf_log_c_err"
 	exit_message="$1 ($exit_status)"
 	exit_beep="$conf_log_beep_err"
-	exit_defer _environment_dump
 	exit_defer _exit_log_app_exit
+	exit_defer _environment_dump
 	_exit_run_defers
 	exit $exit_status
 }
@@ -135,7 +140,7 @@ _exit_print_line() {
 	printf '  %s @ %s:%s\n' "$_exception_line" $0 $1
 }
 exit_defer() {
-	log_debug "deferring: $1"
+	log_debug "deferring: $*"
 	if [ $# -gt 1 ]; then
 		local _defer_with_args
 		_defer_with_args=$(printf '%s' "$*" | sed -e 's/ /:/' -e 's/ /,/g')
@@ -144,6 +149,26 @@ exit_defer() {
 		exit_defers="$1 $exit_defers"
 	fi
 }
+exit_undefer() {
+	log_debug "undeferring: $*"
+	local _undefer_target
+	if [ $# -gt 1 ]; then
+		_undefer_target=$(printf '%s' "$*" | sed -e 's/ /:/' -e 's/ /,/g')
+	else
+		_undefer_target="$1"
+	fi
+	local _new_defers=""
+	local _defer
+	for _defer in $exit_defers; do
+		if [ "$_defer" != "$_undefer_target" ]; then
+			_new_defers="$_defer $_new_defers"
+		fi
+	done
+	exit_defers=""
+	for _defer in $_new_defers; do
+		exit_defers="$_defer $exit_defers"
+	done
+}
 _exit_run_defers() {
 	[ -z "$exit_defers" ] && return 1
 	for exit_defer in $exit_defers; do
@@ -151,10 +176,10 @@ _exit_run_defers() {
 		*:*)
 			local _func_name=$(printf '%s' "$exit_defer" | cut -d':' -f1)
 			local _args=$(printf '%s' "$exit_defer" | cut -d':' -f2 | tr ',' ' ')
-			exec_call $_func_name $_args 2>/dev/null
+			exec_call $_func_name $_args
 			;;
 		*)
-			exec_call $exit_defer 2>/dev/null
+			exec_call $exit_defer
 			;;
 		esac
 	done
@@ -162,21 +187,23 @@ _exit_run_defers() {
 }
 _exit_log_app_exit() {
 	[ "$exit_message" ] && {
-		if [ -z "$APPLICATION_START_TIME" ]; then
-			unset exit_beep
-		else
-			local _current_time
-			local _timeout
-			_current_time=$(date +%s)
-			_timeout=$(($APPLICATION_START_TIME + $conf_log_beep_timeout))
-			[ $_current_time -le $_timeout ] && unset exit_beep
-		fi
+		_exit_disable_beep
 		log_print_log $exit_log_level "$exit_status_code" "$exit_color_code" "$exit_beep" "$exit_message"
 	}
 	log_app exit
 	[ -n "$log_logfile" ] && [ -n "$optn_log_exit_cmd" ] && {
 		$optn_log_exit_cmd -file $log_logfile
 	}
+}
+_exit_disable_beep() {
+	[ -z "$APPLICATION_START_TIME" ] && {
+		unset exit_beep
+		return
+	}
+	local _current_time=$(date +%s)
+	local _timeout=$(($APPLICATION_START_TIME + $conf_log_beep_timeout))
+	[ $_current_time -ge $_timeout ] && return
+	unset exit_beep
 }
 _help_print() {
 	if [ -e $2 ]; then
@@ -237,17 +264,20 @@ _include_optional() {
 	unset inc_file inc_dir
 	[ "$inc_err" -eq 0 ]
 }
-log_warn() {
-	log_print_log 3 WRN "${conf_log_c_wrn}" "${conf_log_beep_wrn}" "$1"
+log_to_console() {
+	[ -z "$interactive" ] && return 0
+	local _color=$1 _event_date_time=$2 _message=$3
+	if [ "$conf_log_date_time_to_console" -eq 1 ]; then
+		printf >/dev/tty '\033[%s%s - %s \033[0m\n' "$_color" "$_event_date_time" "$_message"
+	else
+		printf >/dev/tty '\033[%s%s \033[0m\n' "$_color" "$_message"
+	fi
 }
-log_info() {
-	log_print_log 2 INF "${conf_log_c_info}" "${conf_log_beep_info}" "$1"
+log_print_to_console() {
+	printf >/dev/tty "%s" "$1"
 }
-log_detail() {
-	log_print_log 2 DTL "${conf_log_c_detail}" "${conf_log_beep_detail}" "$1"
-}
-log_debug() {
-	log_print_log 1 DBG "${conf_log_c_debug}" "${conf_log_beep_debug}" "($$) $1"
+log_print_newline_to_console() {
+	printf >/dev/tty '\n'
 }
 log_add_context() {
 	[ -z "$1" ] && return 1
@@ -273,26 +303,9 @@ log_remove_context() {
 		;;
 	esac
 }
-log_to_console() {
-	[ -z "$conf_log_console" ] && return 0
-	local _color=$1 _message=$2
-	printf >&${conf_log_console} '\033[%s%s \033[0m\n' "$_color" "$_message"
-}
-log_print_to_console() {
-	printf >&${conf_log_console} "%s" "$1"
-}
-log_print_newline_to_console() {
-	printf >&${conf_log_console} '\n'
-}
-log_colorize_text() {
-	printf '\033[%s%s\033[0m' "$1" "$2"
-}
-log_sanitize_input() {
-	sed -e 's/\x1b\[[0-9;]*[mGKH]//g' -e 's/[^[:print:][:space:]]//g' -e 's/  */ /g' -e 's/^ //' -e 's/ $//'
-}
 log_to_file() {
 	[ -z "$log_logfile" ] && return 0
-	printf '%s %s %s\n' "$(date '+%Y/%m/%d %H:%M:%S')" "$1" "$2" >>$log_logfile
+	printf '%s %s %s\n' "$1" "$2" "$3" >>$log_logfile
 }
 log_open_logfile() {
 	less +G $log_logfile
@@ -311,6 +324,30 @@ log_move_logfile() {
 		cat "$original_logfile" >>"$log_logfile"
 		rm -f "$original_logfile"
 	fi
+}
+log_set_logfile() {
+	[ -z "$1" ] && return
+	log_logfile="$(_file_readlink $(dirname $1))/$(basename $1)"
+	mkdir -p $(dirname $log_logfile)
+	log_to_console "${conf_log_c_wrn}" "        writing logs to ${log_logfile}${log_msg}"
+}
+log_warn() {
+	log_print_log 3 WRN "${conf_log_c_wrn}" "${conf_log_beep_wrn}" "$1"
+}
+log_info() {
+	log_print_log 2 INF "${conf_log_c_info}" "${conf_log_beep_info}" "$1"
+}
+log_detail() {
+	log_print_log 2 DTL "${conf_log_c_detail}" "${conf_log_beep_detail}" "$1"
+}
+log_debug() {
+	log_print_log 1 DBG "${conf_log_c_debug}" "${conf_log_beep_debug}" "($$) $1"
+}
+log_colorize_text() {
+	printf '\033[%s%s\033[0m' "$1" "$2"
+}
+log_sanitize_input() {
+	sed -e 's/\x1b\[[0-9;]*[mGKH]//g' -e 's/[^[:print:][:space:]]//g' -e 's/  */ /g' -e 's/^ //' -e 's/ $//'
 }
 log_init() {
 	[ -n "$log_logfile" ] && log_set_logfile "$log_logfile"
@@ -331,70 +368,18 @@ log_enable_debug_mode() {
 	}
 	set -x
 }
-log_set_logfile() {
-	[ -z "$1" ] && return
-	if ! { >&3; } 2>/dev/null; then
-		exec 3>&1 4>&2
-	fi
-	[ -n "$log_fifo_pid" ] && log_reset_logging
-	log_logfile="$(_file_readlink $(dirname $1))/$(basename $1)"
-	if [ -z "$log_no_indent" ]; then
-		log_redirect_output_with_indent
-	else
-		log_redirect_output
-	fi
-	conf_log_console=4
-	log_to_console "${conf_log_c_wrn}" "        writing logs to ${log_logfile}${log_msg}"
-}
-log_redirect_output_with_indent() {
-	log_fifo="$log_logfile.fifo"
-	mkfifo "$log_fifo" || {
-		log_warn "error setting up fifo, falling back to std redirection"
-		unset log_fifo
-		log_redirect_output
-		return
-	}
-	sed -u 's/^/    /' <"$log_fifo" >>"$log_logfile" &
-	log_fifo_pid=$!
-	exit_defer log_reset_logging
-	exec >"$log_fifo" 2>&1
-}
-log_reset_logging() {
-	unset logging_context
-	exec 1>&3 2>&4
-	log_cleanup_logging
-}
-log_cleanup_logging() {
-	[ -n "$log_fifo_pid" ] && {
-		timeout -k 5 -s SIGTERM 1 wait $log_fifo_pid 2>/dev/null
-		unset log_fifo_pid
-	}
-	[ -n "$log_fifo" ] && {
-		rm -f $log_fifo 2>/dev/null
-		unset log_fifo
-	}
-}
-log_redirect_output() {
-	exec >>"$log_logfile" 2>&1
-}
 log_print_log() {
 	local _level=$1 _level_str=$2 _color=$3 _tone=$4 _message="$5"
 	[ $_level -lt $conf_log_level ] && return 0
 	[ -n "$logging_context" ] &&
 		_message="${logging_context} - ${_message}"
-	log_handle_background_notification "$_level_str" "$_message"
-	[ -n "$_tone" ] && _beep_beep "$_tone"
-	log_to_file "$_level_str" "$_message"
-	log_to_console "$_color" "$_message"
-	log_user_log "$_level_str" "$_message"
+	[ -n "$_tone" ] && [ $beep_enabled -eq 1 ] && _beep_beep "$_tone"
+	local log_event_date_time="$(date '+%Y/%m/%d %H:%M:%S')"
+	log_to_file "$_level_str" "$log_event_date_time" "$_message"
+	log_to_console "$_color" "$log_event_date_time" "$_message"
+	log_user_log "$_level_str" "$log_event_date_time" "$_message"
 	[ -n "$log_syslog" ] && _syslog_syslog "$_message"
 	return 0
-}
-log_handle_background_notification() {
-	local _level_str=$1 _message=$2
-	[ -z "$backgrounded" ] && return
-	[ -z "$optn_install_background_notification_method" ] && return
-	$optn_install_background_notification_method "$_level_str" "$_message" &
 }
 log_app() {
 	log_debug "$APPLICATION_NAME:$APPLICATION_CMD - $1 ($$)"
@@ -559,6 +544,26 @@ validation_require() {
 	}
 	exit_with_error "$2 required $required_message" $3
 }
+_mail_send() {
+	[ -n "$conf_log_mail_disabled" ] && {
+		log_warn "mail is disabled"
+		return 1
+	}
+	if [ $# -lt 3 ]; then
+		log_warn "recipients[0], subject[1], message[2] is required - $# arguments provided"
+		return 2
+	fi
+	local _recipients
+	_recipients=$(printf '%s' "$1" | tr '|' ' ')
+	shift
+	local _subject
+	_subject="$1"
+	shift
+	local _message
+	_message="$1"
+	shift
+	printf '%s\n' "$_message" | mail -s "$_subject" $_recipients
+}
 _alert_alert() {
 	local _recipients
 	local _subject
@@ -578,7 +583,7 @@ _alert_alert() {
 		log_debug "recipients is empty, aborting"
 		return 1
 	fi
-	_mail "$_recipients" "$_subject" "$2"
+	_mail_send "$_recipients" "$_subject" "$2"
 }
 _alert_long_running_cmd() {
 	[ -n "$optn_disable_long_running_cmd_notification" ] && return
@@ -611,7 +616,6 @@ _extension_main() {
 			continue
 		}
 		extension_feature_name=${extension_action}_${extension_run_type}
-		extension_run_type_name=$(printf '%s' $extension_run_type | tr '-' '_')
 		_is_feature_enabled $extension_feature_name || {
 			log_debug "skipping feature: $extension_feature_name | $extension_run_type - disabled"
 			unset extension_feature_name
@@ -668,6 +672,8 @@ _extension_find_default_files() {
 	find . -type f -and -name "$_name_pattern" \
 		! -path '*/*.archived/*' \
 		! -path '*/*.secret/*' \
+		! -path '*/*.unused/*' \
+		! -path '*/*.deprecated/*' \
 		! -path '*/node_modules/*' \
 		! -path '*/target/*' \
 		! -path '*/.idea/*' \
@@ -700,67 +706,112 @@ _extension_run() {
 	done
 	return $_error_count
 }
-_agent_extension_create_jobs() {
-	log_add_context create_jobs
-	_agent_git_init_workspace
-	for agent_persona_job in $(find /usr/local/walterjwhite/agent/personas/$agent_persona -maxdepth 1 -mindepth 1 -type d | sort -V); do
-		_agent_extension_create_job
-	done
-	git add persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_relative_path
-	git commit -m "created jobs for $agent_persona - $agent_project"
-	git push
+_agent_extension_create_job() {
+	agent_job_git_repository=$(git remote -v | head -1 | awk {'print$2'})
+	agent_project=$(basename $agent_job_git_repository | sed -e 's/\.git$//')
+	agent_extension_type=$extension_run_type
+	validation_require "$agent_job_git_repository" agent_job_git_repository
+	log_add_context $agent_job_relative_path
+	_agent_load_job_cfg
+	[ -n "$agent_persona_job_disabled" ] && {
+		_agent_log_persona_job_no_run "disabled"
+		log_remove_context
+		return 1
+	}
+	_agent_write_job
 	log_remove_context
 }
-_agent_extension_create_job() {
-	agent_job_name=$(basename $agent_persona_job)
-	log_add_context $agent_job_name
+_agent_write_job() {
 	log_detail "creating job"
-	mkdir -p persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_relative_path/$agent_job_name
-	cp $agent_persona_job/prompt.md persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_relative_path/$agent_job_name/
+	mkdir -p $agent_workspace/persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_name/$agent_job_relative_path
+	file_require $agent_persona_job/prompt.md
+	cp $agent_persona_job/prompt.md $agent_workspace/persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_name/$agent_job_relative_path
 	(
 		printf 'agent_job_git_repository=%s\n' "$agent_job_git_repository"
 		printf 'agent_extension_type=%s\n' "$agent_extension_type"
-	) >persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_relative_path/$agent_job_name/job
+		[ -n "$all_file_extensions" ] && printf 'all_file_extensions=1\n'
+	) >$agent_workspace/persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_name/$agent_job_relative_path/job
 	[ -n "$agent_job_relative_path" ] && {
 		log_warn "batch"
 		(
 			printf "_agent_job_batcher() {\n"
 			printf "  printf '%s\\\n'\n" $agent_job_relative_path
 			printf '}\n'
-		) >>persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_relative_path/$agent_job_name/job
+		) >>$agent_workspace/persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_name/$agent_job_relative_path/job
 	}
-	log_remove_context
+}
+_agent_load_job_cfg() {
+	_include_optional $git_worktree_path/.secret/agent/$agent_persona/$agent_job_name_key \
+		$git_worktree_path/$agent_job_relative_path/.secret/agent/$agent_persona/$agent_job_name_key
+}
+_agent_log_persona_job_no_run() {
+	log_warn "$1"
+	unset agent_persona_job_disabled
 }
 agent_extension_batch() {
-	_extension_load_type
-	local batch_opwd=$PWD
-	local batch_dir
-	for batch_dir in $(extension_find_dirs_containing); do
-		cd $batch_dir
-		_agent_extension "$@"
-		cd $batch_opwd
-	done
-}
-_agent_extension() {
 	log_add_context "persona-$agent_persona"
-	agent_job_git_repository=$(git remote -v | head -1 | awk {'print$2'})
-	agent_project=$(basename $agent_job_git_repository | sed -e 's/\.git$//')
-	agent_extension_type=$extension_run_type
-	[ "$(git rev-parse --show-toplevel)" != "$(pwd)" ] && {
-		agent_job_relative_path=$(_git_relative_path_in_worktree)
-	}
-	validation_require "$agent_job_git_repository" agent_job_git_repository
-	_agent_extension_create_jobs
-	_agent_extension_run_jobs
+	_extension_load_type
+	agent_invocation_wd=$PWD
+	_agent_git_init_workspace
+	for agent_persona_job in $(find /usr/local/walterjwhite/agent/personas/$agent_persona -maxdepth 1 -mindepth 1 -type d | sort -V); do
+		agent_job_name=$(basename $agent_persona_job)
+		_agent_get_job_name_key
+		log_add_context $agent_job_name_key
+		_agent_extension_create_batches_for_persona_job
+		_agent_extension_run_jobs
+		log_remove_context
+	done
 	log_remove_context
+}
+_agent_extension_create_batches_for_persona_job() {
+	cd $agent_invocation_wd
+	for agent_job_relative_path in $(extension_find_dirs_containing | sort -r); do
+		[ -n "$agent_batch_skip_root" ] && [ "$batch_dir" = "." ] && {
+			log_warn "skipping root dir"
+			continue
+		}
+		_agent_extension_create_job
+	done
+	cd $agent_workspace
+	git add persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_name
+	git commit -m "created jobs for $agent_persona - $agent_project"
+	git push
+	unset agent_job_relative_path
 }
 _agent_extension_run_jobs() {
 	log_add_context run_jobs
 	log_detail "$batch_dir | $PWD"
-	for agent_job in $(find persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_relative_path -type d -name '*.job' | sort -V); do
-		agent-worker $agent_job
+	_agent_get_job_name_key
+	for agent_job in $(find persona/$agent_persona/$agent_project/$extension_run_type/$agent_job_name -type d ! -name log | sort -r); do
+		agent-worker $agent_job &
+		agent_worker_pid=$!
+		exit_defer kill -9 $agent_worker_pid
+		_agent_extension_tail_logs &
+		agent_tail_pid=$!
+		exit_defer kill -9 $agent_tail_pid
+		wait $agent_worker_pid
+		local worker_exit=$?
+		[ -n "$agent_tail_pid" ] && kill $agent_tail_pid 2>/dev/null
+		[ $worker_exit -ne 0 ] && {
+			log_warn "job did not complete successfully: $worker_exit"
+		}
 	done
 	log_remove_context
+}
+_agent_extension_tail_logs() {
+	sleep 1
+	local child_log_dir="$agent_job/log"
+	local child_log_file=$(ls -t "$child_log_dir" 2>/dev/null | head -1)
+	[ -n "$child_log_file" ] && {
+		child_log_file="$child_log_dir/$child_log_file"
+		log_detail "launching log viewer: $log_logfile | $child_log_file"
+		tail -f $child_log_file
+		git add $child_log_file
+		git commit $child_log_file -m "$agent_job logs"
+		git push
+		return
+	}
+	log_warn "unable to initialize log viewer: $log_logfile | $child_log_file"
 }
 _is_feature_enabled() {
 	local feature_key=$(_feature_key $1)
@@ -774,23 +825,31 @@ _feature_key() {
 	printf '%s\n' "feature_${1}" | tr '-' '_'
 }
 _git_relative_path_in_worktree() {
-	local worktree_path=$(git rev-parse --show-toplevel)
-	pwd | sed -e "s|^$worktree_path/||"
+	git_worktree_path=$(git rev-parse --show-toplevel)
+	git_relative_path_in_worktree=$(pwd | sed -e "s|^$git_worktree_path/||")
 }
 _agent_git_init_workspace() {
 	[ ! -e $agent_workspace ] && {
 		log_detail 'initializing workspace'
-		git clone $conf_agent_git_repository_prefix/$(head -1 /usr/local/etc/walterjwhite/system)/$USER/agent-work.git $agent_workspace
+		system_id=$(_system_get_id)
+		git clone $conf_agent_git_repository_prefix/$system_id/$USER/agent-work.git $agent_workspace
 	}
 	log_detail 'updating workspace'
 	cd $agent_workspace
 	gpull
+}
+_agent_get_job_name_key() {
+	agent_job_name_key="${agent_job_name#[0-9][0-9].}"
+	agent_job_name_key="${agent_job_name_key%.job}"
 }
 _path_in_path() {
 	local _check_path=$1
 	validation_require "$_check_path" _path_in_path
 	local test_path=$(readlink -f "$_check_path")
 	readlink -f "$PWD" | grep -c "^$test_path" >/dev/null 2>&1
+}
+_system_get_id() {
+	head -1 ${APP_PLATFORM_ROOT}${PLATFORM_SYSTEM_ID_PATH} 2>/dev/null
 }
 readonly APPLICATION_NAME=agent
 readonly APPLICATION_START_TIME=$(date +%s)
@@ -833,7 +892,6 @@ readonly LIBRARY_PATH=/usr/local/walterjwhite
 readonly BIN_PATH=/usr/local/bin
 case $APP_PLATFORM_SUB_PLATFORM in
 Arch | CachyOS)
-	linux_package_manager=pacman
 	case $APP_PLATFORM_SUB_PLATFORM in
 	CachyOS)
 		readonly APP_PLATFORM_DERIVED_SUB_PLATFORM=Arch
@@ -843,13 +901,12 @@ Arch | CachyOS)
 	readonly NPM_PACKAGE="npm"
 	readonly RUST_PACKAGE="rust"
 	readonly PYPI_PACKAGE="python"
-	readonly GO_PACKAGE="go"
+	readonly GO_PACKAGE="go gcc"
 	readonly EXPECT_PACKAGE="expect"
 	: ${pacman_silent_install:=1}
 	: ${pacman_auto_install:=1}
 	;;
 Gentoo)
-	linux_package_manager=emerge
 	readonly PLATFORM_PACKAGES="dev-vcs/git dev-tcltk/expect net-misc/curl dev-util/sh app-admin/sudo app-misc/beep app-portage/gentoolkit"
 	readonly PLATFORM_PACKAGES_ACCEPT_KEYWORDS="dev-util/sh ~amd64"
 	readonly NPM_PACKAGE="net-libs/nodejs"
@@ -874,20 +931,19 @@ readonly APP_LIBRARY_PATH=$APP_PLATFORM_LIBRARY_PATH/$APPLICATION_NAME
 readonly REQUIRED_ARGUMENTS="agent_persona:Agent Persona"
 _include_optional . agent beep context logging net paths platform wait
 _metadata_load
-: ${RSRC_BEEP:=/tmp/beep}
+: ${beep_enabled:=0}
 : ${conf_log_beep_timeout:=5}
-: ${conf_log_beep_ERR:='-f 1000 -l 1000'}
-: ${conf_log_beep_ALRT:='-f 1000 -l 100 -n -f 1000 -l 100'}
-: ${conf_log_beep_SCS:='-f 1600 -l 100'}
-: ${conf_log_beep_WRN:='-f 1500 -l 100 -n -f 1000'}
+: ${conf_log_beep_err:='-f 1000 -l 1000'}
+: ${conf_log_beep_alrt:='-f 1000 -l 100 -n -f 1000 -l 100'}
+: ${conf_log_beep_scs:='-f 1600 -l 100'}
+: ${conf_log_beep_wrn:='-f 1500 -l 100 -n -f 1000'}
 : ${conf_log_beep_info:=''}
 : ${conf_log_beep_detail:=''}
 : ${conf_log_beep_debug:=''}
-: ${conf_log_beep_STDIN:='-f 1000 -l 100 -n -f 1400'}
+: ${conf_log_beep_stdin:='-f 1000 -l 100 -n -f 1400'}
 : ${conf_log_sudo_beep_tone:='-f 1000 -l 100 -n -f 1400 -l 50 -n -f 1200'}
 : ${APP_CONTEXT:=$_CONSOLE_CONTEXT_ID}
 : ${APP_CONTEXT:=default}
-CONF_LOG_HEADER="##################################################"
 : ${conf_log_c_err:="1;31m"}
 : ${conf_log_c_scs:="1;32m"}
 : ${conf_log_c_wrn:="1;33m"}
@@ -904,9 +960,9 @@ CONF_LOG_HEADER="##################################################"
 : ${conf_log_feature_timeout_error_level:=warn}
 : ${conf_log_long_running_cmd:=30}
 : ${conf_log_long_running_cmd_lines:=1000}
+: ${conf_log_date_time_to_console:=0}
 which mail >/dev/null 2>&1 || conf_log_mail_disabled=1
-[ -t 0 ] && interactive=1
-: ${conf_log_console:=2}
+[ -t 2 ] && [ -c /dev/tty ] && interactive=1
 : ${conf_network_test_timeout:=5}
 : ${conf_network_test_targets:="http://connectivity-check.ubuntu.com http://example.org http://www.google.com http://telehack.com http://lxer.com"}
 : ${emerge_portage_refresh_period:=3600}
@@ -997,3 +1053,4 @@ wait_waitee_init
 wait_waiter
 sudo_ensure_not_root
 _extension_main "$@"
+readonly REQUIRED_APP_CONF="conf_agent_git_repository_prefix"
diff --git a/firewall/Linux/setup/nftables.feature/setup/bin/_nftables-update-table b/firewall/Linux/setup/nftables.feature/setup/bin/_nftables-update-table
--- a/firewall/Linux/setup/nftables.feature/setup/bin/_nftables-update-table
+++ b/firewall/Linux/setup/nftables.feature/setup/bin/_nftables-update-table
@@ -52,8 +52,13 @@ _exec_do_exec() {
 	log_info "$*"
 	local _exit_status
 	if [ -z "$dry_run" ]; then
-		"$@"
-		_exit_status=$?
+		if [ -z "$log_logfile" ]; then
+			"$@"
+			_exit_status=$?
+		else
+			"$@" 2>&1 | sed -u 's/^/    /' | tee -a "$log_logfile"
+			_exit_status=$?
+		fi
 	else
 		log_warn "using dry run status: $dry_run"
 		_exit_status=$dry_run
@@ -88,8 +93,8 @@ exit_with_error() {
 	exit_color_code="$conf_log_c_err"
 	exit_message="$1 ($exit_status)"
 	exit_beep="$conf_log_beep_err"
-	exit_defer _environment_dump
 	exit_defer _exit_log_app_exit
+	exit_defer _environment_dump
 	_exit_run_defers
 	exit $exit_status
 }
@@ -135,7 +140,7 @@ _exit_print_line() {
 	printf '  %s @ %s:%s\n' "$_exception_line" $0 $1
 }
 exit_defer() {
-	log_debug "deferring: $1"
+	log_debug "deferring: $*"
 	if [ $# -gt 1 ]; then
 		local _defer_with_args
 		_defer_with_args=$(printf '%s' "$*" | sed -e 's/ /:/' -e 's/ /,/g')
@@ -144,6 +149,26 @@ exit_defer() {
 		exit_defers="$1 $exit_defers"
 	fi
 }
+exit_undefer() {
+	log_debug "undeferring: $*"
+	local _undefer_target
+	if [ $# -gt 1 ]; then
+		_undefer_target=$(printf '%s' "$*" | sed -e 's/ /:/' -e 's/ /,/g')
+	else
+		_undefer_target="$1"
+	fi
+	local _new_defers=""
+	local _defer
+	for _defer in $exit_defers; do
+		if [ "$_defer" != "$_undefer_target" ]; then
+			_new_defers="$_defer $_new_defers"
+		fi
+	done
+	exit_defers=""
+	for _defer in $_new_defers; do
+		exit_defers="$_defer $exit_defers"
+	done
+}
 _exit_run_defers() {
 	[ -z "$exit_defers" ] && return 1
 	for exit_defer in $exit_defers; do
@@ -151,10 +176,10 @@ _exit_run_defers() {
 		*:*)
 			local _func_name=$(printf '%s' "$exit_defer" | cut -d':' -f1)
 			local _args=$(printf '%s' "$exit_defer" | cut -d':' -f2 | tr ',' ' ')
-			exec_call $_func_name $_args 2>/dev/null
+			exec_call $_func_name $_args
 			;;
 		*)
-			exec_call $exit_defer 2>/dev/null
+			exec_call $exit_defer
 			;;
 		esac
 	done
@@ -162,21 +187,23 @@ _exit_run_defers() {
 }
 _exit_log_app_exit() {
 	[ "$exit_message" ] && {
-		if [ -z "$APPLICATION_START_TIME" ]; then
-			unset exit_beep
-		else
-			local _current_time
-			local _timeout
-			_current_time=$(date +%s)
-			_timeout=$(($APPLICATION_START_TIME + $conf_log_beep_timeout))
-			[ $_current_time -le $_timeout ] && unset exit_beep
-		fi
+		_exit_disable_beep
 		log_print_log $exit_log_level "$exit_status_code" "$exit_color_code" "$exit_beep" "$exit_message"
 	}
 	log_app exit
 	[ -n "$log_logfile" ] && [ -n "$optn_log_exit_cmd" ] && {
 		$optn_log_exit_cmd -file $log_logfile
 	}
+}
+_exit_disable_beep() {
+	[ -z "$APPLICATION_START_TIME" ] && {
+		unset exit_beep
+		return
+	}
+	local _current_time=$(date +%s)
+	local _timeout=$(($APPLICATION_START_TIME + $conf_log_beep_timeout))
+	[ $_current_time -ge $_timeout ] && return
+	unset exit_beep
 }
 _help_print() {
 	if [ -e $2 ]; then
@@ -237,17 +264,20 @@ _include_optional() {
 	unset inc_file inc_dir
 	[ "$inc_err" -eq 0 ]
 }
-log_warn() {
-	log_print_log 3 WRN "${conf_log_c_wrn}" "${conf_log_beep_wrn}" "$1"
+log_to_console() {
+	[ -z "$interactive" ] && return 0
+	local _color=$1 _event_date_time=$2 _message=$3
+	if [ "$conf_log_date_time_to_console" -eq 1 ]; then
+		printf >/dev/tty '\033[%s%s - %s \033[0m\n' "$_color" "$_event_date_time" "$_message"
+	else
+		printf >/dev/tty '\033[%s%s \033[0m\n' "$_color" "$_message"
+	fi
 }
-log_info() {
-	log_print_log 2 INF "${conf_log_c_info}" "${conf_log_beep_info}" "$1"
+log_print_to_console() {
+	printf >/dev/tty "%s" "$1"
 }
-log_detail() {
-	log_print_log 2 DTL "${conf_log_c_detail}" "${conf_log_beep_detail}" "$1"
-}
-log_debug() {
-	log_print_log 1 DBG "${conf_log_c_debug}" "${conf_log_beep_debug}" "($$) $1"
+log_print_newline_to_console() {
+	printf >/dev/tty '\n'
 }
 log_add_context() {
 	[ -z "$1" ] && return 1
@@ -273,26 +303,9 @@ log_remove_context() {
 		;;
 	esac
 }
-log_to_console() {
-	[ -z "$conf_log_console" ] && return 0
-	local _color=$1 _message=$2
-	printf >&${conf_log_console} '\033[%s%s \033[0m\n' "$_color" "$_message"
-}
-log_print_to_console() {
-	printf >&${conf_log_console} "%s" "$1"
-}
-log_print_newline_to_console() {
-	printf >&${conf_log_console} '\n'
-}
-log_colorize_text() {
-	printf '\033[%s%s\033[0m' "$1" "$2"
-}
-log_sanitize_input() {
-	sed -e 's/\x1b\[[0-9;]*[mGKH]//g' -e 's/[^[:print:][:space:]]//g' -e 's/  */ /g' -e 's/^ //' -e 's/ $//'
-}
 log_to_file() {
 	[ -z "$log_logfile" ] && return 0
-	printf '%s %s %s\n' "$(date '+%Y/%m/%d %H:%M:%S')" "$1" "$2" >>$log_logfile
+	printf '%s %s %s\n' "$1" "$2" "$3" >>$log_logfile
 }
 log_open_logfile() {
 	less +G $log_logfile
@@ -311,6 +324,30 @@ log_move_logfile() {
 		cat "$original_logfile" >>"$log_logfile"
 		rm -f "$original_logfile"
 	fi
+}
+log_set_logfile() {
+	[ -z "$1" ] && return
+	log_logfile="$(_file_readlink $(dirname $1))/$(basename $1)"
+	mkdir -p $(dirname $log_logfile)
+	log_to_console "${conf_log_c_wrn}" "        writing logs to ${log_logfile}${log_msg}"
+}
+log_warn() {
+	log_print_log 3 WRN "${conf_log_c_wrn}" "${conf_log_beep_wrn}" "$1"
+}
+log_info() {
+	log_print_log 2 INF "${conf_log_c_info}" "${conf_log_beep_info}" "$1"
+}
+log_detail() {
+	log_print_log 2 DTL "${conf_log_c_detail}" "${conf_log_beep_detail}" "$1"
+}
+log_debug() {
+	log_print_log 1 DBG "${conf_log_c_debug}" "${conf_log_beep_debug}" "($$) $1"
+}
+log_colorize_text() {
+	printf '\033[%s%s\033[0m' "$1" "$2"
+}
+log_sanitize_input() {
+	sed -e 's/\x1b\[[0-9;]*[mGKH]//g' -e 's/[^[:print:][:space:]]//g' -e 's/  */ /g' -e 's/^ //' -e 's/ $//'
 }
 log_init() {
 	[ -n "$log_logfile" ] && log_set_logfile "$log_logfile"
@@ -331,70 +368,18 @@ log_enable_debug_mode() {
 	}
 	set -x
 }
-log_set_logfile() {
-	[ -z "$1" ] && return
-	if ! { >&3; } 2>/dev/null; then
-		exec 3>&1 4>&2
-	fi
-	[ -n "$log_fifo_pid" ] && log_reset_logging
-	log_logfile="$(_file_readlink $(dirname $1))/$(basename $1)"
-	if [ -z "$log_no_indent" ]; then
-		log_redirect_output_with_indent
-	else
-		log_redirect_output
-	fi
-	conf_log_console=4
-	log_to_console "${conf_log_c_wrn}" "        writing logs to ${log_logfile}${log_msg}"
-}
-log_redirect_output_with_indent() {
-	log_fifo="$log_logfile.fifo"
-	mkfifo "$log_fifo" || {
-		log_warn "error setting up fifo, falling back to std redirection"
-		unset log_fifo
-		log_redirect_output
-		return
-	}
-	sed -u 's/^/    /' <"$log_fifo" >>"$log_logfile" &
-	log_fifo_pid=$!
-	exit_defer log_reset_logging
-	exec >"$log_fifo" 2>&1
-}
-log_reset_logging() {
-	unset logging_context
-	exec 1>&3 2>&4
-	log_cleanup_logging
-}
-log_cleanup_logging() {
-	[ -n "$log_fifo_pid" ] && {
-		timeout -k 5 -s SIGTERM 1 wait $log_fifo_pid 2>/dev/null
-		unset log_fifo_pid
-	}
-	[ -n "$log_fifo" ] && {
-		rm -f $log_fifo 2>/dev/null
-		unset log_fifo
-	}
-}
-log_redirect_output() {
-	exec >>"$log_logfile" 2>&1
-}
 log_print_log() {
 	local _level=$1 _level_str=$2 _color=$3 _tone=$4 _message="$5"
 	[ $_level -lt $conf_log_level ] && return 0
 	[ -n "$logging_context" ] &&
 		_message="${logging_context} - ${_message}"
-	log_handle_background_notification "$_level_str" "$_message"
-	[ -n "$_tone" ] && _beep_beep "$_tone"
-	log_to_file "$_level_str" "$_message"
-	log_to_console "$_color" "$_message"
-	log_user_log "$_level_str" "$_message"
+	[ -n "$_tone" ] && [ $beep_enabled -eq 1 ] && _beep_beep "$_tone"
+	local log_event_date_time="$(date '+%Y/%m/%d %H:%M:%S')"
+	log_to_file "$_level_str" "$log_event_date_time" "$_message"
+	log_to_console "$_color" "$log_event_date_time" "$_message"
+	log_user_log "$_level_str" "$log_event_date_time" "$_message"
 	[ -n "$log_syslog" ] && _syslog_syslog "$_message"
 	return 0
-}
-log_handle_background_notification() {
-	local _level_str=$1 _message=$2
-	[ -z "$backgrounded" ] && return
-	[ -z "$optn_install_background_notification_method" ] && return
-	$optn_install_background_notification_method "$_level_str" "$_message" &
 }
 log_app() {
 	log_debug "$APPLICATION_NAME:$APPLICATION_CMD - $1 ($$)"
@@ -559,6 +544,26 @@ validation_require() {
 	}
 	exit_with_error "$2 required $required_message" $3
 }
+_mail_send() {
+	[ -n "$conf_log_mail_disabled" ] && {
+		log_warn "mail is disabled"
+		return 1
+	}
+	if [ $# -lt 3 ]; then
+		log_warn "recipients[0], subject[1], message[2] is required - $# arguments provided"
+		return 2
+	fi
+	local _recipients
+	_recipients=$(printf '%s' "$1" | tr '|' ' ')
+	shift
+	local _subject
+	_subject="$1"
+	shift
+	local _message
+	_message="$1"
+	shift
+	printf '%s\n' "$_message" | mail -s "$_subject" $_recipients
+}
 _alert_alert() {
 	local _recipients
 	local _subject
@@ -578,7 +583,7 @@ _alert_alert() {
 		log_debug "recipients is empty, aborting"
 		return 1
 	fi
-	_mail "$_recipients" "$_subject" "$2"
+	_mail_send "$_recipients" "$_subject" "$2"
 }
 _alert_long_running_cmd() {
 	[ -n "$optn_disable_long_running_cmd_notification" ] && return
@@ -637,7 +642,6 @@ readonly LIBRARY_PATH=/usr/local/walterjwhite
 readonly BIN_PATH=/usr/local/bin
 case $APP_PLATFORM_SUB_PLATFORM in
 Arch | CachyOS)
-	linux_package_manager=pacman
 	case $APP_PLATFORM_SUB_PLATFORM in
 	CachyOS)
 		readonly APP_PLATFORM_DERIVED_SUB_PLATFORM=Arch
@@ -647,13 +651,12 @@ Arch | CachyOS)
 	readonly NPM_PACKAGE="npm"
 	readonly RUST_PACKAGE="rust"
 	readonly PYPI_PACKAGE="python"
-	readonly GO_PACKAGE="go"
+	readonly GO_PACKAGE="go gcc"
 	readonly EXPECT_PACKAGE="expect"
 	: ${pacman_silent_install:=1}
 	: ${pacman_auto_install:=1}
 	;;
 Gentoo)
-	linux_package_manager=emerge
 	readonly PLATFORM_PACKAGES="dev-vcs/git dev-tcltk/expect net-misc/curl dev-util/sh app-admin/sudo app-misc/beep app-portage/gentoolkit"
 	readonly PLATFORM_PACKAGES_ACCEPT_KEYWORDS="dev-util/sh ~amd64"
 	readonly NPM_PACKAGE="net-libs/nodejs"
@@ -678,20 +681,19 @@ readonly APP_LIBRARY_PATH=$APP_PLATFORM_LIBRARY_PATH/$APPLICATION_NAME
 readonly REQUIRED_ARGUMENTS="_NFTABLES_SET_NAME:nftables set name|_NFTABLES_SET_DATA_FILE:nftables set filename"
 _include_optional beep context firewall logging net paths platform wait
 _metadata_load
-: ${RSRC_BEEP:=/tmp/beep}
+: ${beep_enabled:=0}
 : ${conf_log_beep_timeout:=5}
-: ${conf_log_beep_ERR:='-f 1000 -l 1000'}
-: ${conf_log_beep_ALRT:='-f 1000 -l 100 -n -f 1000 -l 100'}
-: ${conf_log_beep_SCS:='-f 1600 -l 100'}
-: ${conf_log_beep_WRN:='-f 1500 -l 100 -n -f 1000'}
+: ${conf_log_beep_err:='-f 1000 -l 1000'}
+: ${conf_log_beep_alrt:='-f 1000 -l 100 -n -f 1000 -l 100'}
+: ${conf_log_beep_scs:='-f 1600 -l 100'}
+: ${conf_log_beep_wrn:='-f 1500 -l 100 -n -f 1000'}
 : ${conf_log_beep_info:=''}
 : ${conf_log_beep_detail:=''}
 : ${conf_log_beep_debug:=''}
-: ${conf_log_beep_STDIN:='-f 1000 -l 100 -n -f 1400'}
+: ${conf_log_beep_stdin:='-f 1000 -l 100 -n -f 1400'}
 : ${conf_log_sudo_beep_tone:='-f 1000 -l 100 -n -f 1400 -l 50 -n -f 1200'}
 : ${APP_CONTEXT:=$_CONSOLE_CONTEXT_ID}
 : ${APP_CONTEXT:=default}
-CONF_LOG_HEADER="##################################################"
 : ${conf_log_c_err:="1;31m"}
 : ${conf_log_c_scs:="1;32m"}
 : ${conf_log_c_wrn:="1;33m"}
@@ -708,9 +710,9 @@ CONF_LOG_HEADER="##################################################"
 : ${conf_log_feature_timeout_error_level:=warn}
 : ${conf_log_long_running_cmd:=30}
 : ${conf_log_long_running_cmd_lines:=1000}
+: ${conf_log_date_time_to_console:=0}
 which mail >/dev/null 2>&1 || conf_log_mail_disabled=1
-[ -t 0 ] && interactive=1
-: ${conf_log_console:=2}
+[ -t 2 ] && [ -c /dev/tty ] && interactive=1
 : ${conf_network_test_timeout:=5}
 : ${conf_network_test_targets:="http://connectivity-check.ubuntu.com http://example.org http://www.google.com http://telehack.com http://lxer.com"}
 : ${emerge_portage_refresh_period:=3600}
diff --git a/install/Linux/setup/bin/app-run b/install/Linux/setup/bin/app-run
--- a/install/Linux/setup/bin/app-run
+++ b/install/Linux/setup/bin/app-run
@@ -52,8 +52,13 @@ _exec_do_exec() {
 	log_info "$*"
 	local _exit_status
 	if [ -z "$dry_run" ]; then
-		"$@"
-		_exit_status=$?
+		if [ -z "$log_logfile" ]; then
+			"$@"
+			_exit_status=$?
+		else
+			"$@" 2>&1 | sed -u 's/^/    /' | tee -a "$log_logfile"
+			_exit_status=$?
+		fi
 	else
 		log_warn "using dry run status: $dry_run"
 		_exit_status=$dry_run
@@ -88,8 +93,8 @@ exit_with_error() {
 	exit_color_code="$conf_log_c_err"
 	exit_message="$1 ($exit_status)"
 	exit_beep="$conf_log_beep_err"
-	exit_defer _environment_dump
 	exit_defer _exit_log_app_exit
+	exit_defer _environment_dump
 	_exit_run_defers
 	exit $exit_status
 }
@@ -135,7 +140,7 @@ _exit_print_line() {
 	printf '  %s @ %s:%s\n' "$_exception_line" $0 $1
 }
 exit_defer() {
-	log_debug "deferring: $1"
+	log_debug "deferring: $*"
 	if [ $# -gt 1 ]; then
 		local _defer_with_args
 		_defer_with_args=$(printf '%s' "$*" | sed -e 's/ /:/' -e 's/ /,/g')
@@ -144,6 +149,26 @@ exit_defer() {
 		exit_defers="$1 $exit_defers"
 	fi
 }
+exit_undefer() {
+	log_debug "undeferring: $*"
+	local _undefer_target
+	if [ $# -gt 1 ]; then
+		_undefer_target=$(printf '%s' "$*" | sed -e 's/ /:/' -e 's/ /,/g')
+	else
+		_undefer_target="$1"
+	fi
+	local _new_defers=""
+	local _defer
+	for _defer in $exit_defers; do
+		if [ "$_defer" != "$_undefer_target" ]; then
+			_new_defers="$_defer $_new_defers"
+		fi
+	done
+	exit_defers=""
+	for _defer in $_new_defers; do
+		exit_defers="$_defer $exit_defers"
+	done
+}
 _exit_run_defers() {
 	[ -z "$exit_defers" ] && return 1
 	for exit_defer in $exit_defers; do
@@ -151,10 +176,10 @@ _exit_run_defers() {
 		*:*)
 			local _func_name=$(printf '%s' "$exit_defer" | cut -d':' -f1)
 			local _args=$(printf '%s' "$exit_defer" | cut -d':' -f2 | tr ',' ' ')
-			exec_call $_func_name $_args 2>/dev/null
+			exec_call $_func_name $_args
 			;;
 		*)
-			exec_call $exit_defer 2>/dev/null
+			exec_call $exit_defer
 			;;
 		esac
 	done
@@ -162,21 +187,23 @@ _exit_run_defers() {
 }
 _exit_log_app_exit() {
 	[ "$exit_message" ] && {
-		if [ -z "$APPLICATION_START_TIME" ]; then
-			unset exit_beep
-		else
-			local _current_time
-			local _timeout
-			_current_time=$(date +%s)
-			_timeout=$(($APPLICATION_START_TIME + $conf_log_beep_timeout))
-			[ $_current_time -le $_timeout ] && unset exit_beep
-		fi
+		_exit_disable_beep
 		log_print_log $exit_log_level "$exit_status_code" "$exit_color_code" "$exit_beep" "$exit_message"
 	}
 	log_app exit
 	[ -n "$log_logfile" ] && [ -n "$optn_log_exit_cmd" ] && {
 		$optn_log_exit_cmd -file $log_logfile
 	}
+}
+_exit_disable_beep() {
+	[ -z "$APPLICATION_START_TIME" ] && {
+		unset exit_beep
+		return
+	}
+	local _current_time=$(date +%s)
+	local _timeout=$(($APPLICATION_START_TIME + $conf_log_beep_timeout))
+	[ $_current_time -ge $_timeout ] && return
+	unset exit_beep
 }
 _help_print() {
 	if [ -e $2 ]; then
@@ -237,17 +264,20 @@ _include_optional() {
 	unset inc_file inc_dir
 	[ "$inc_err" -eq 0 ]
 }
-log_warn() {
-	log_print_log 3 WRN "${conf_log_c_wrn}" "${conf_log_beep_wrn}" "$1"
+log_to_console() {
+	[ -z "$interactive" ] && return 0
+	local _color=$1 _event_date_time=$2 _message=$3
+	if [ "$conf_log_date_time_to_console" -eq 1 ]; then
+		printf >/dev/tty '\033[%s%s - %s \033[0m\n' "$_color" "$_event_date_time" "$_message"
+	else
+		printf >/dev/tty '\033[%s%s \033[0m\n' "$_color" "$_message"
+	fi
 }
-log_info() {
-	log_print_log 2 INF "${conf_log_c_info}" "${conf_log_beep_info}" "$1"
+log_print_to_console() {
+	printf >/dev/tty "%s" "$1"
 }
-log_detail() {
-	log_print_log 2 DTL "${conf_log_c_detail}" "${conf_log_beep_detail}" "$1"
-}
-log_debug() {
-	log_print_log 1 DBG "${conf_log_c_debug}" "${conf_log_beep_debug}" "($$) $1"
+log_print_newline_to_console() {
+	printf >/dev/tty '\n'
 }
 log_add_context() {
 	[ -z "$1" ] && return 1
@@ -273,26 +303,9 @@ log_remove_context() {
 		;;
 	esac
 }
-log_to_console() {
-	[ -z "$conf_log_console" ] && return 0
-	local _color=$1 _message=$2
-	printf >&${conf_log_console} '\033[%s%s \033[0m\n' "$_color" "$_message"
-}
-log_print_to_console() {
-	printf >&${conf_log_console} "%s" "$1"
-}
-log_print_newline_to_console() {
-	printf >&${conf_log_console} '\n'
-}
-log_colorize_text() {
-	printf '\033[%s%s\033[0m' "$1" "$2"
-}
-log_sanitize_input() {
-	sed -e 's/\x1b\[[0-9;]*[mGKH]//g' -e 's/[^[:print:][:space:]]//g' -e 's/  */ /g' -e 's/^ //' -e 's/ $//'
-}
 log_to_file() {
 	[ -z "$log_logfile" ] && return 0
-	printf '%s %s %s\n' "$(date '+%Y/%m/%d %H:%M:%S')" "$1" "$2" >>$log_logfile
+	printf '%s %s %s\n' "$1" "$2" "$3" >>$log_logfile
 }
 log_open_logfile() {
 	less +G $log_logfile
@@ -311,6 +324,30 @@ log_move_logfile() {
 		cat "$original_logfile" >>"$log_logfile"
 		rm -f "$original_logfile"
 	fi
+}
+log_set_logfile() {
+	[ -z "$1" ] && return
+	log_logfile="$(_file_readlink $(dirname $1))/$(basename $1)"
+	mkdir -p $(dirname $log_logfile)
+	log_to_console "${conf_log_c_wrn}" "        writing logs to ${log_logfile}${log_msg}"
+}
+log_warn() {
+	log_print_log 3 WRN "${conf_log_c_wrn}" "${conf_log_beep_wrn}" "$1"
+}
+log_info() {
+	log_print_log 2 INF "${conf_log_c_info}" "${conf_log_beep_info}" "$1"
+}
+log_detail() {
+	log_print_log 2 DTL "${conf_log_c_detail}" "${conf_log_beep_detail}" "$1"
+}
+log_debug() {
+	log_print_log 1 DBG "${conf_log_c_debug}" "${conf_log_beep_debug}" "($$) $1"
+}
+log_colorize_text() {
+	printf '\033[%s%s\033[0m' "$1" "$2"
+}
+log_sanitize_input() {
+	sed -e 's/\x1b\[[0-9;]*[mGKH]//g' -e 's/[^[:print:][:space:]]//g' -e 's/  */ /g' -e 's/^ //' -e 's/ $//'
 }
 log_init() {
 	[ -n "$log_logfile" ] && log_set_logfile "$log_logfile"
@@ -331,70 +368,18 @@ log_enable_debug_mode() {
 	}
 	set -x
 }
-log_set_logfile() {
-	[ -z "$1" ] && return
-	if ! { >&3; } 2>/dev/null; then
-		exec 3>&1 4>&2
-	fi
-	[ -n "$log_fifo_pid" ] && log_reset_logging
-	log_logfile="$(_file_readlink $(dirname $1))/$(basename $1)"
-	if [ -z "$log_no_indent" ]; then
-		log_redirect_output_with_indent
-	else
-		log_redirect_output
-	fi
-	conf_log_console=4
-	log_to_console "${conf_log_c_wrn}" "        writing logs to ${log_logfile}${log_msg}"
-}
-log_redirect_output_with_indent() {
-	log_fifo="$log_logfile.fifo"
-	mkfifo "$log_fifo" || {
-		log_warn "error setting up fifo, falling back to std redirection"
-		unset log_fifo
-		log_redirect_output
-		return
-	}
-	sed -u 's/^/    /' <"$log_fifo" >>"$log_logfile" &
-	log_fifo_pid=$!
-	exit_defer log_reset_logging
-	exec >"$log_fifo" 2>&1
-}
-log_reset_logging() {
-	unset logging_context
-	exec 1>&3 2>&4
-	log_cleanup_logging
-}
-log_cleanup_logging() {
-	[ -n "$log_fifo_pid" ] && {
-		timeout -k 5 -s SIGTERM 1 wait $log_fifo_pid 2>/dev/null
-		unset log_fifo_pid
-	}
-	[ -n "$log_fifo" ] && {
-		rm -f $log_fifo 2>/dev/null
-		unset log_fifo
-	}
-}
-log_redirect_output() {
-	exec >>"$log_logfile" 2>&1
-}
 log_print_log() {
 	local _level=$1 _level_str=$2 _color=$3 _tone=$4 _message="$5"
 	[ $_level -lt $conf_log_level ] && return 0
 	[ -n "$logging_context" ] &&
 		_message="${logging_context} - ${_message}"
-	log_handle_background_notification "$_level_str" "$_message"
-	[ -n "$_tone" ] && _beep_beep "$_tone"
-	log_to_file "$_level_str" "$_message"
-	log_to_console "$_color" "$_message"
-	log_user_log "$_level_str" "$_message"
+	[ -n "$_tone" ] && [ $beep_enabled -eq 1 ] && _beep_beep "$_tone"
+	local log_event_date_time="$(date '+%Y/%m/%d %H:%M:%S')"
+	log_to_file "$_level_str" "$log_event_date_time" "$_message"
+	log_to_console "$_color" "$log_event_date_time" "$_message"
+	log_user_log "$_level_str" "$log_event_date_time" "$_message"
 	[ -n "$log_syslog" ] && _syslog_syslog "$_message"
 	return 0
-}
-log_handle_background_notification() {
-	local _level_str=$1 _message=$2
-	[ -z "$backgrounded" ] && return
-	[ -z "$optn_install_background_notification_method" ] && return
-	$optn_install_background_notification_method "$_level_str" "$_message" &
 }
 log_app() {
 	log_debug "$APPLICATION_NAME:$APPLICATION_CMD - $1 ($$)"
@@ -559,6 +544,26 @@ validation_require() {
 	}
 	exit_with_error "$2 required $required_message" $3
 }
+_mail_send() {
+	[ -n "$conf_log_mail_disabled" ] && {
+		log_warn "mail is disabled"
+		return 1
+	}
+	if [ $# -lt 3 ]; then
+		log_warn "recipients[0], subject[1], message[2] is required - $# arguments provided"
+		return 2
+	fi
+	local _recipients
+	_recipients=$(printf '%s' "$1" | tr '|' ' ')
+	shift
+	local _subject
+	_subject="$1"
+	shift
+	local _message
+	_message="$1"
+	shift
+	printf '%s\n' "$_message" | mail -s "$_subject" $_recipients
+}
 _alert_alert() {
 	local _recipients
 	local _subject
@@ -578,7 +583,7 @@ _alert_alert() {
 		log_debug "recipients is empty, aborting"
 		return 1
 	fi
-	_mail "$_recipients" "$_subject" "$2"
+	_mail_send "$_recipients" "$_subject" "$2"
 }
 _alert_long_running_cmd() {
 	[ -n "$optn_disable_long_running_cmd_notification" ] && return
@@ -831,7 +836,6 @@ _buildfile_inject_full() {
 	: ${cfg_imports:="$BUILDFILE_FULL_CFG ./$target_application_name"}
 	buildfile_optional=1 before_function=_buildfile_inject_cfg_before _buildfile_imports cfg $1 "$cfg_imports"
 	unset buildfile_included_cfg
-	printf 'readonly REQUIRED_APP_CONF=""\n' >>$buildfile_output_package_file
 	: ${init_imports:="$BUILDFILE_FULL_INIT"}
 	buildfile_optional=1 _buildfile_imports init $1 "$init_imports"
 	chmod +x $buildfile_output_package_file $1
@@ -865,44 +869,31 @@ validation_required_arguments() {
 }
 validation_required_cfg() {
 	local required_cfg=$($GNU_GREP -Pvh '#.*$' $buildfile_output_package_file |
-		$GNU_GREP -Poh '\$_CONF_[\w_]{3,}' | sed -e 's/^\$//' | sort -u)
-	local defaults=$($GNU_GREP -Poh '_CONF_[\w]{3,}:?=' $buildfile_output_package_file | sed -e 's/^\$//' -e 's/:=$//' -e 's/=$//' | sort -u | tr '\n' '|' | sed -e 's/|$//' -e 's/^/(/' -e 's/$/)/')
+		$GNU_GREP -Poh '\$conf_[\w_]{3,}' | sed -e 's/^\$//' | sort -u)
+	local defaults=$($GNU_GREP -Poh 'conf_[\w]{3,}:?=' $buildfile_output_package_file | sed -e 's/^\$//' -e 's/:=$//' -e 's/=$//' | sort -u | tr '\n' '|' | sed -e 's/|$//' -e 's/^/(/' -e 's/$/)/')
 	buildfile_required_app_conf=$(printf '%s\n' "$required_cfg" | $GNU_GREP -Pv "$defaults" | tr '\n' ' ' | sed -e 's/ $//')
-	if [ -n "$buildfile_required_app_conf" ]; then
-		$GNU_SED -i "s/^readonly REQUIRED_APP_CONF=.*/buildfile_required_app_conf=\"$buildfile_required_app_conf\"/" $buildfile_output_package_file
-	else
-		$GNU_SED -i "/^readonly REQUIRED_APP_CONF=.*/d" $buildfile_output_package_file
-	fi
+	[ -n "$buildfile_required_app_conf" ] && printf 'readonly REQUIRED_APP_CONF="%s"\n' "$buildfile_required_app_conf" >>$buildfile_output_package_file
 }
 _buildfile_list_variables() {
-	$GNU_GREP -Pho '\$(\{?)[\w]{3,}(:?)=' $1 | sed -e 's/^\${//' -e 's/^\$//' -e 's/:=//' -e 's/=//' | sort -u
+	{
+		$GNU_GREP -Pho '\$(\{?)[\w]{3,}(:?)=' $1 | sed -e 's/^\${//' -e 's/^\$//' -e 's/:=//' -e 's/=//'
+		$GNU_GREP -Pho '^[[:space:]]*[\w]{3,}=' $1 | sed -e 's/^[[:space:]]*//' -e 's/=//'
+	} | sort -u
 }
 _buildfile_used_variables() {
 	$GNU_GREP -Po '\$({?)[\w]{3,}' $1 | sed -e 's/^\${//' -e 's/^\$//' | sort -u
-	grep export $1 | $GNU_GREP -Pho '\$(\{?)[\w]{3,}' | sed -e 's/^\${//' -e 's/^\$//'
-	grep set $1 | $GNU_GREP -Pho '\$(\{?)[\w]{3,}' | sed -e 's/^\${//' -e 's/^\$//'
+	$GNU_GREP -P '^[[:space:]]*(export|set) [\w]{3,}' $1 | $GNU_GREP -Pho '\$(\{?)[\w]{3,}' | sed -e 's/^\${//' -e 's/^\$//'
 }
 _buildfile_unused_variables() {
 	local used_variables=$(_buildfile_used_variables $buildfile_output_package_file | tr '\n' '|' | sed -e 's/^/(/' -e 's/|$//' -e 's/$/)/')
-	local dynamic_variables=$(_buildfile_dynamic_variables | tr '\n' '|' | sed -e 's/^/(/' -e 's/|$//' -e 's/$/)/')
-	local candidates=$(_buildfile_list_variables $buildfile_output_package_file | $GNU_GREP -Pv "^${used_variables}$")
-	if [ "$dynamic_variables" != "()" ]; then
-		printf '%s\n' "$candidates" | $GNU_GREP -Pv "^${dynamic_variables}$"
-	else
-		printf '%s\n' "$candidates"
-	fi
-}
-_buildfile_dynamic_variables() {
-	$GNU_GREP -Po '_[a-z0-9_]*\$\{[a-z0-9_]+\}[a-z0-9_\$]*' $buildfile_output_package_file |
-		sed -e 's/\${[^}]*}/[a-z0-9_]*/g' |
-		sort -u
+	_buildfile_list_variables $buildfile_output_package_file | $GNU_GREP -Pv "^${used_variables}$"
 }
 _buildfile_remove_unused_variables() {
 	local buildfile_index=0
 	while :; do
 		local unused_variables=$(_buildfile_unused_variables)
 		[ -z "$unused_variables" ] && break
-		log_debug "remove cfg:$i:$unused_variables"
+		log_detail "remove cfg:$i:$unused_variables"
 		local unused_variable
 		for unused_variable in $unused_variables; do
 			_buildfile_remove_unused_variable $unused_variable $buildfile_output_package_file
@@ -911,7 +902,7 @@ _buildfile_remove_unused_variables() {
 	done
 }
 _buildfile_remove_unused_variable() {
-	log_debug "unused default: $1"
+	log_warn "unused default: $1"
 	$GNU_SED -i "/^[[:space:]]*: \${$1:=.*}$/d" $2
 	$GNU_SED -i -E "/^[[:space:]]*((export|readonly|local)[[:space:]]+)?$1=.*/d" $2
 }
@@ -1007,7 +998,7 @@ EOF
 	exit_with_error "$buildfile_output_package_file has constants missing namespace prefix (Rule 3 - must have any NAMESPACE_ prefix)"
 }
 _buildfile_duplicate_functions_find() {
-	local duplicated_functions=$($GNU_GREP -Po '[_a-zA-Z][_a-zA-Z0-9]*\(\)' $buildfile_output_package_file | $GNU_SED -e 's/()//' | uniq -d | sort -u)
+	local duplicated_functions=$($GNU_GREP -Po '^[_a-zA-Z][_a-zA-Z0-9]*\(\)[[:space:]]*\{' $buildfile_output_package_file | $GNU_SED -e 's/().*//' | uniq -d | sort -u)
 	[ -z "$duplicated_functions" ] && return
 	log_warn 'duplicated functions'
 	printf '%s\n' "$duplicated_functions"
@@ -1173,8 +1164,6 @@ _build_list_referenced_commands() {
     s/[(){}]/ /g;
   " "$buildfile_output_package_file" | awk '
     BEGIN {
-      validation_keywords="if then elif else fi while until do done in esac function time ! ["
-      skip_line="for select case"
       split(validation_keywords, kw, " ")
       for (i in kw) is_kw[kw[i]] = 1
       split(skip_line, sk, " ")
@@ -1411,7 +1400,6 @@ readonly LIBRARY_PATH=/usr/local/walterjwhite
 readonly BIN_PATH=/usr/local/bin
 case $APP_PLATFORM_SUB_PLATFORM in
 Arch | CachyOS)
-	linux_package_manager=pacman
 	case $APP_PLATFORM_SUB_PLATFORM in
 	CachyOS)
 		readonly APP_PLATFORM_DERIVED_SUB_PLATFORM=Arch
@@ -1421,13 +1409,12 @@ Arch | CachyOS)
 	readonly NPM_PACKAGE="npm"
 	readonly RUST_PACKAGE="rust"
 	readonly PYPI_PACKAGE="python"
-	readonly GO_PACKAGE="go"
+	readonly GO_PACKAGE="go gcc"
 	readonly EXPECT_PACKAGE="expect"
 	: ${pacman_silent_install:=1}
 	: ${pacman_auto_install:=1}
 	;;
 Gentoo)
-	linux_package_manager=emerge
 	readonly PLATFORM_PACKAGES="dev-vcs/git dev-tcltk/expect net-misc/curl dev-util/sh app-admin/sudo app-misc/beep app-portage/gentoolkit"
 	readonly PLATFORM_PACKAGES_ACCEPT_KEYWORDS="dev-util/sh ~amd64"
 	readonly NPM_PACKAGE="net-libs/nodejs"
@@ -1452,24 +1439,22 @@ readonly APP_LIBRARY_PATH=$APP_PLATFORM_LIBRARY_PATH/$APPLICATION_NAME
 readonly APPLICATION_METADATA_PATH=$APP_LIBRARY_PATH/install/.metadata
 readonly ARTIFACTS_PATH=/tmp/$USER/walterjwhite/$APPLICATION_NAME/artifacts
 readonly REGISTRY_PATH=$DATA_PATH/$APPLICATION_NAME/registry
-readonly WALTERJWHITE_GO_APPLICATION_PACKAGE_PREFIX=github.com/walterjwhite/go-code/lib/application
 readonly REQUIRED_ARGUMENTS="_RUN_FILE:The file to compile and run"
 _include_optional beep context install logging net paths platform wait
 _metadata_load
-: ${RSRC_BEEP:=/tmp/beep}
+: ${beep_enabled:=0}
 : ${conf_log_beep_timeout:=5}
-: ${conf_log_beep_ERR:='-f 1000 -l 1000'}
-: ${conf_log_beep_ALRT:='-f 1000 -l 100 -n -f 1000 -l 100'}
-: ${conf_log_beep_SCS:='-f 1600 -l 100'}
-: ${conf_log_beep_WRN:='-f 1500 -l 100 -n -f 1000'}
+: ${conf_log_beep_err:='-f 1000 -l 1000'}
+: ${conf_log_beep_alrt:='-f 1000 -l 100 -n -f 1000 -l 100'}
+: ${conf_log_beep_scs:='-f 1600 -l 100'}
+: ${conf_log_beep_wrn:='-f 1500 -l 100 -n -f 1000'}
 : ${conf_log_beep_info:=''}
 : ${conf_log_beep_detail:=''}
 : ${conf_log_beep_debug:=''}
-: ${conf_log_beep_STDIN:='-f 1000 -l 100 -n -f 1400'}
+: ${conf_log_beep_stdin:='-f 1000 -l 100 -n -f 1400'}
 : ${conf_log_sudo_beep_tone:='-f 1000 -l 100 -n -f 1400 -l 50 -n -f 1200'}
 : ${APP_CONTEXT:=$_CONSOLE_CONTEXT_ID}
 : ${APP_CONTEXT:=default}
-CONF_LOG_HEADER="##################################################"
 : ${conf_log_c_err:="1;31m"}
 : ${conf_log_c_scs:="1;32m"}
 : ${conf_log_c_wrn:="1;33m"}
@@ -1486,9 +1471,9 @@ CONF_LOG_HEADER="##################################################"
 : ${conf_log_feature_timeout_error_level:=warn}
 : ${conf_log_long_running_cmd:=30}
 : ${conf_log_long_running_cmd_lines:=1000}
+: ${conf_log_date_time_to_console:=0}
 which mail >/dev/null 2>&1 || conf_log_mail_disabled=1
-[ -t 0 ] && interactive=1
-: ${conf_log_console:=2}
+[ -t 2 ] && [ -c /dev/tty ] && interactive=1
 : ${conf_network_test_timeout:=5}
 : ${conf_network_test_targets:="http://connectivity-check.ubuntu.com http://example.org http://www.google.com http://telehack.com http://lxer.com"}
 : ${emerge_portage_refresh_period:=3600}
